# Generated by Django 3.1.5 on 2021-02-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcontactemail',
            name='from_email',
            field=models.EmailField(max_length=60, verbose_name='Email'),
        ),
    ]
