# Generated by Django 3.1.5 on 2021-01-14 19:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210114_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default=django.utils.timezone.now, max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
