# Generated by Django 3.1.5 on 2021-01-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210114_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(max_length=150),
        ),
    ]
