# Generated by Django 3.1.5 on 2021-01-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210114_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='naira.jpg', upload_to='profile_pics'),
        ),
    ]
