# Generated by Django 3.1.5 on 2021-01-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_user_full_name2'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name2',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
