# Generated by Django 3.1.5 on 2021-01-17 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_user_full_name2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name2',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
