# Generated by Django 3.1.5 on 2021-01-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20210117_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name2',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
