"""
Django settings for yurilima project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import mimetypes

from decouple import config
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)
# config('DEBUG', default=False, cast=bool)

#MIME type Django
# mimetypes.add_type("text/css", ".css", True)
# mimetypes.add_type("text/scss", ".scss", True)
# mimetypes.add_type("text/plain", ".js", True)
# mimetypes.add_type("text/javascript", ".js", True)
# mimetypes.add_type("application/javascript", ".js", True)
# mimetypes.add_type("application/x-javascript", ".js", True)

ALLOWED_HOSTS = ['yurilima.herokuapp.com','www.yurilima.com.br', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    # The following apps are required:
    # Django Apps    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    # 'django.contrib.sites',
    'django.contrib.sitemaps',
    # Local Apps
    'users.apps.UsersConfig',
    'blog.apps.BlogConfig',
    'emails.apps.EmailsConfig',
    'yurilimacv.apps.YurilimacvConfig',
    # 3rd Party
    'crispy_forms', #https://django-crispy-forms.readthedocs.io/en/latest/ --- https://simpleisbetterthancomplex.com/tutorial/2018/11/28/advanced-form-rendering-with-django-crispy-forms.html
    "anymail",
    'tinymce',
    'mathfilters',
    'google_analytics'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'yurilima.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'yurilima.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

#Authetications Redirects
LOGOUT_REDIRECT_URL = 'painel-list'#After login they goes to home page
LOGIN_REDIRECT_URL = 'painel-list'#After login they goes to home page
LOGIN_URL = 'login'#if the user is not logged in, they redirect to login page

#Static Paths
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

#AWS S3
# STATICFILES_STORAGE = 'storages.backends.s3boto3.S3StaticStorage'

#Media Paths #https://overiq.com/django-1-10/handling-media-files-in-django/
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

AUTH_USER_MODEL = 'users.User'

# Django Crispy Forms
CRISPY_TEMPLATE_PACK = 'bootstrap4'

#Settings SMTP email
#https://www.youtube.com/watch?v=NxARIts_wls
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST =config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT', cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')

#Settings API email
# EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"  # or sendgrid.EmailBackend, or...
DEFAULT_FROM_EMAIL = "y.m.lima19@gmail.com"  # if you don't already have this in settings
SERVER_EMAIL = "y.m.lima19@gmail.com"  # ditto (default from-email for Django errors)


#AWS S3 Buckets Config
# https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html
AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

#Tiny API Key 
TINYMCE_JS_URL = os.path.join(MEDIA_URL, "tinymce/tinymce.min.js")
TINYMCE_SPELLCHECKER = True
TINYMCE_COMPRESSOR = False
TINYMCE_DEFAULT_CONFIG = {
    # 'selector':'form-group',
    "height": "520px",
    "width": "1280px",
    "menubar": "file edit view insert format tools table help",

    'quickbars_selection_toolbar': 'bold italic | quicklink h2 h3 blockquote quickimage quicktable',

    "plugins": "advlist autolink lists link image charmap print preview anchor searchreplace visualblocks code "

    "fullscreen insertdatetime media table paste code help wordcount spellchecker codesample",

    "toolbar": "undo redo | bold italic underline strikethrough | fontselect fontsizeselect formatselect | alignleft "

    "aligncenter alignright alignjustify | outdent indent |  numlist bullist checklist | forecolor "

    "fullscreen  preview save print | insertfile image media pageembed template link anchor codesample | "

    "backcolor casechange permanentpen formatpainter removeformat | pagebreak | charmap emoticons | "

    "a11ycheck ltr rtl | showcomments addcomment code",

    "custom_undo_redo_levels": 10,

    'codesample_global_prismjs': 'true',

    'toolbar_mode': 'sliding',
    
    # "language": "en-Us",  # To force a specific language instead of the Django current language.
}
GOOGLE_ANALYTICS = {
    'google_analytics_id': 'G-J4BGZKBT6W',
}




# STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"