# Generated by Django 3.1.5 on 2021-01-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
