# Generated by Django 3.1.5 on 2021-01-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210114_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='number_of_comments',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='number_of_pingbacks',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
