# Generated by Django 3.1.5 on 2021-01-14 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210114_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_email',
        ),
    ]
