# Generated by Django 3.1.5 on 2021-01-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210119_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contact_number',
            field=models.CharField(blank=True, help_text='If you have another way to comunicate.', max_length=20),
        ),
    ]
