# Generated by Django 3.1.5 on 2021-01-23 13:37

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210119_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content2',
            field=djrichtextfield.models.RichTextField(null=True),
        ),
    ]
