# Generated by Django 3.1.5 on 2021-01-23 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_content2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content2',
        ),
    ]
