# Generated by Django 3.1.5 on 2021-01-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_post_content2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contentleft',
            field=models.TextField(help_text='Write your Post', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='contentright',
            field=models.TextField(help_text='Write the Opposite Post', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='urlleft',
            field=models.URLField(help_text='Paste here the link, witch you saw that news?', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='urlright',
            field=models.URLField(help_text='Paste here the link, witch you saw that news?', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(help_text='Paste here the link, witch you saw that news?'),
        ),
    ]
