# Generated by Django 3.1.5 on 2021-01-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210131_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Painel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='contentleft',
        ),
        migrations.RemoveField(
            model_name='post',
            name='contentright',
        ),
        migrations.RemoveField(
            model_name='post',
            name='urlleft',
        ),
        migrations.RemoveField(
            model_name='post',
            name='urlright',
        ),
    ]
