# Generated by Django 3.1.5 on 2021-02-03 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210203_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='painel',
            old_name='date_posted',
            new_name='painel_date_posted',
        ),
        migrations.RenameField(
            model_name='painel',
            old_name='date_updated',
            new_name='painel_date_updated',
        ),
    ]
