# Generated by Django 3.1.5 on 2021-02-03 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20210203_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='painel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.painel'),
        ),
    ]
