# Generated by Django 3.1.5 on 2021-02-08 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20210207_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='Descriptions', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Your Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(default='www.yurilima.com', help_text='Paste here the link, witch you saw that news?'),
        ),
    ]
