# Generated by Django 3.1.5 on 2021-02-08 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0021_auto_20210208_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painel',
            name='created_by',
            field=models.ForeignKey(blank=True, default='users.User', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='painel',
            name='hashtag',
            field=models.CharField(default='Your hashtag here', max_length=255, null=True, unique=True),
        ),
    ]
