# Generated by Django 3.1.5 on 2021-02-15 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20210208_0020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='painel',
            options={'ordering': ['-painel_date_posted']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_posted']},
        ),
    ]
