# Generated by Django 3.1.5 on 2021-02-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20210215_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(help_text='Paste here the link, witch you saw that news ou inspirations?'),
        ),
    ]
