# Generated by Django 3.1.5 on 2021-03-10 20:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20210217_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_post',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content'),
        ),
    ]
